#!/usr/bin/ruby

application   = ARGV[0].to_s
app_file = File.join(application, "app.rb")
required_gems = [:rubygems, :sinata, :data_mapper]
directories   = [:views, :public, :lib].collect{|dir| File.join(application, dir.to_s)}

def make_it(dir)
  File.exists?(dir) ? puts("#{dir} exists") : Dir.mkdir(dir)
end

def make_file(f)
  File.exists?(f) ? puts("#{f} exists") : (puts "Creating #{f}";file = File.open(f, "a"))
  file
end

[application, directories].flatten.each{|d| make_it d}

f = make_file(app_file)

unless f.nil?
  required_gems.each{|g| f.puts "require \"#{g}\""}
  f.close
end

system "mate #{application}" if File.exists?("/Applications/TextMate.app")
